/**
 * The curation queue.
 *
 * Every run rewrites `WORKLIST.md` with the upcoming days still on a
 * placeholder, soonest first. That ordering is the whole point: the queue
 * prioritises itself, and a curator works from the top.
 */

import { daysBetween } from './dates.js';
import type { Subject } from './emit/subject.js';

export interface WorklistItem {
  readonly date: string;
  readonly subject: Subject;
  readonly rank: string;
  readonly color: string;
}

/** How far ahead the worklist looks. Beyond this the queue is noise. */
export const WORKLIST_HORIZON_DAYS = 120;

/** How many distinct subjects to list. */
export const WORKLIST_LIMIT = 60;

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|');
}

/**
 * Renders the worklist.
 *
 * Items are grouped by subject id: a saint whose day recurs, or an id shared by
 * several dates, is one job for the curator, not several. The group takes the
 * date of its soonest occurrence.
 */
export function renderWorklist(today: string, items: readonly WorklistItem[]): string {
  const upcoming = items
    .filter((item) => {
      const offset = daysBetween(today, item.date);
      return offset >= 0 && offset <= WORKLIST_HORIZON_DAYS;
    })
    .sort((a, b) =>
      a.date === b.date ? a.subject.id.localeCompare(b.subject.id) : a.date.localeCompare(b.date),
    );

  const groups = new Map<string, { first: WorklistItem; dates: string[] }>();
  for (const item of upcoming) {
    const group = groups.get(item.subject.id);
    if (group) {
      group.dates.push(item.date);
    } else {
      groups.set(item.subject.id, { first: item, dates: [item.date] });
    }
  }

  const rows = [...groups.values()].slice(0, WORKLIST_LIMIT);

  const lines: string[] = [
    '# Curation worklist',
    '',
    '<!-- Generated by `npm run generate`. Do not edit by hand. -->',
    '',
    'Upcoming days still showing a generic liturgical-colour plate, soonest first.',
    'To claim one, add `saints/{id}.yaml` and `originals/{id}.jpg` — see',
    '[CONTRIBUTING.md](CONTRIBUTING.md). Anything curated goes live on the next run.',
    '',
  ];

  if (rows.length === 0) {
    lines.push(`Nothing outstanding in the next ${WORKLIST_HORIZON_DAYS} days.`, '');
    return lines.join('\n');
  }

  lines.push(
    `${groups.size} subject(s) outstanding in the next ${WORKLIST_HORIZON_DAYS} days` +
      (groups.size > rows.length ? `; the ${rows.length} soonest are listed.` : '.'),
    '',
    '| Next date | Kind | Id | Subject | Rank | Colour |',
    '| --- | --- | --- | --- | --- | --- |',
  );

  for (const { first, dates } of rows) {
    const date = dates.length > 1 ? `${first.date} (+${dates.length - 1})` : first.date;
    // `saint` marks a person in the martyrology; `day` is a Sunday, ferial
    // weekday or solemnity of the Lord, where a curated image is optional
    // polish rather than a missing saint.
    const kind = first.subject.isSanctoral ? 'saint' : 'day';
    lines.push(
      `| ${date} | ${kind} | \`${escapeCell(first.subject.id)}\` |` +
        ` ${escapeCell(first.subject.name)} | ${escapeCell(first.rank)} | ${escapeCell(first.color)} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
